version: 0.1
log:
  accesslog:
    disabled: true
  level: info
  formatter: text
storage:
  filesystem:
  delete:
    enabled: true
auth:
  htpasswd:
    realm: Transfer
    path: /data/auth/htpasswd
notifications:
  endpoints:
    - name: notify
      url: http://localhost:5555
      timeout: 500ms
      threshold: 5
      backoff: 1s
http:
  addr: 0.0.0.0:5000
  debug:
    addr: 0.0.0.0:5001
